version: "3.9"

services:
  bucket:
    build: .
    container_name: django-bucket
    ports:
      - "8040:8000"
    volumes:
      - ./media:/app/media
      - ./db.sqlite3:/app/db.sqlite3
    environment:
      - DJANGO_SETTINGS_MODULE=bucket.settings
